### ISSUE TITLE
No sync but high RC level

### ISSUE THREAD

**Issue by m-kalendarev** [SensorsIot/DCF77-Transmitter-for-ESP32#8]
Hi. Tried to get worked on ESP-WROOM-32 but got sync error. I have several Casio RC watches, I can get time with the real Germany signal but got an error with emulated. The watches shows high receiving level, I can see generated time messages in console, even LED is blinking when added to the antenna wire. The antenna is a 20 wire turns around the watches, just for the test. 
Wifi is connected, ntp time is ok.

**Comment by deltazerorsan** [comment]
Hi @m-kalendarev,

Have you tried with less signal? Maybe there is so much signal due to have the watches just in the antenna...

Is the receiving level following the pulses?

**Comment by m-kalendarev** [comment]
Yes I tried, but no luck. I've watched #287 video to understand the antenna connection but the video is about raspberry pi (2 different GPIO outputs connected to antenna), the esp32 has only 1 output to antenna, and I connect it to the coil with 400 ohm   resistor, the other side to the gnd.
upd: Tried all my watches, 2 Seikos and 3 Casios. Seiko gets update quickly, 2-3 min, but Casio shows high reception level for 5-7 min and return err. I have no idea what is the difference because all this watches successfully updated   3-4 times a week with native DE signal placed near the window at night.

**Comment by SensorsIot** [comment]
If the Seikos work, I think, your transmitter works, too. Where else should these watches get the signal?
So the problem is between the transmitter and the Casios or at the Casios. If you have an oscilloscope, I would try to measure the frequency of the transmitter. Maybe it is wrong and the Casios have a better filter. You should also see how the signal looks like.

**Comment by deltazerorsan** [comment]
> Yes I tried, but no luck. I've watched #287 video to understand the antenna connection but the video is about raspberry pi (2 different GPIO outputs connected to antenna), the esp32 has only 1 output to antenna, and I connect it to the coil with 400 ohm resistor, the other side to the gnd. upd: Tried all my watches, 2 Seikos and 3 Casios. Seiko gets update quickly, 2-3 min, but Casio shows high reception level for 5-7 min and return err. I have no idea what is the difference because all this watches successfully updated 3-4 times a week with native DE signal placed near the window at night.

There is a big difference between the raspi and ESP32 implementations. My two Junghans syncronize without trouble with the raspi one but not with the ESP32 one.

In the raspi there is a full signal when pulsing and a 20% (aprox) signal when no pulse. In the ESP32 there is full signal when pulse and NO signal at all when no pulse. That simpler implementation IS NOT the standard and some watches lost syncro because it depends on the carrier frecuency that disapear during no pulse in the case of the ESP32 implementation.

I have a Brigmton Weather Station and some chinesse movements that works with both implemantation, so there is for sure some, as Andreas said, better filtering or more "on the standard" implementations in those watches.

I use the same antenna for both but it is more sofisticated: ferrite, two layers of turns and a capacitor in parallel...

Some time ago I was thinking to adapt the ESP32 implo to the standar but some lack of time and interest...

**Comment by m-kalendarev** [comment]
Hi, thank you for the clarification, I was thinking about it yesterday). Just for an experiment will try raspi with my Casio watches. And will order ferrite rod for LC antenna. The goal was to built in little low consumption transmitter in the wooden watch box and synch all my watches.

**Comment by deltazerorsan** [comment]
Sure mine is not miniaturized...

![photo_2023-01-17_14-22-57](https://user-images.githubusercontent.com/53981858/212910170-92be6553-5b4c-4879-80b7-d168e1786f8a.jpg)

;-)

**Comment by Hamberthm** [comment]
Hi there! I was in the search for a solution to sync a Casio Rangeman watch with RF in a country where none of these signals exists, tried this project and got stuck with this exact problem. Luckily, I solved it, but I ended up using WWVB in another project ([here](https://github.com/motion55/WWVB_Emulator_ESP32/issues/1)), as I couldn't integrate the solution into this one (I tried). It really is somehow simple, what I did is tried to attenuate the signal instead of switching it completely off, and it worked as a charm!

Indeed, Casio watches are very picky about the standard. The original radio transmitter doesn't turn off the carrier completely when signaling a low level, instead it goes down to about 15% power. So these watches won't accept the sync signal as valid unless they detect a continuous carrier presence, even on the low marks.

To solve this, I installed a voltage divider between the antenna and a GPIO pin configured as Open Drain Output, using a 100 Ohm resistor as R1 and 10 Ohm resistor as R2. When R2 is pulled down by the GPIO, signal level is dropped to about 0.3V. R2 sink could be any GPIO configured as Open Drain Output, so it simply offers high impedance when set as HIGH and a current drain to ground when LOW.

Looking at the oscilloscope, the added capacitance from the resistors surely don't give a pretty signal, but I got the watch to accept it with 90% success rate and good range even without a transistor, using only a ferrite antenna.

Software modifications are simple. We only need to configure the new pin as OUTPUT_OPEN_DRAIN, and instead of turning the duty cycle to 0, just set it low when we wish to signal a low level signal and HIGH again for high power. No need to touch the modulation (PWM).

Maybe this is a good and simple followup to this project, @SensorsIot , as it makes it more universally acceptable and closer to the real standard.

**Comment by SensorsIot** [comment]
Thank you for your write-up. It could help somebody with the same problem. Because this is an old project (and it still works here), I will most probably not return to it.

**Comment by deltazerorsan** [comment]
> Hi there! I was in the search for a solution to sync a Casio Rangeman watch with RF in a country where none of these signals exists, tried this project and got stuck with this exact problem. Luckily, I solved it, but I ended up using WWVB in another project ([here](https://github.com/motion55/WWVB_Emulator_ESP32/issues/1)), as I couldn't integrate the solution into this one (I tried). It really is somehow simple, what I did is tried to attenuate the signal instead of switching it completely off, and it worked as a charm!
> 
> Indeed, Casio watches are very picky about the standard. The original radio transmitter doesn't turn off the carrier completely when signaling a low level, instead it goes down to about 15% power. So these watches won't accept the sync signal as valid unless they detect a continuous carrier presence, even on the low marks.
> 
> To solve this, I installed a voltage divider between the antenna and a GPIO pin configured as Open Drain Output, using a 100 Ohm resistor as R1 and 10 Ohm resistor as R2. When R2 is pulled down by the GPIO, signal level is dropped to about 0.3V. R2 sink could be any GPIO configured as Open Drain Output, so it simply offers high impedance when set as HIGH and a current drain to ground when LOW.
> 
> Looking at the oscilloscope, the added capacitance from the resistors surely don't give a pretty signal, but I got the watch to accept it with 90% success rate and good range even without a transistor, using only a ferrite antenna.
> 
> Software modifications are simple. We only need to configure the new pin as OUTPUT_OPEN_DRAIN, and instead of turning the duty cycle to 0, just set it low when we wish to signal a low level signal and HIGH again for high power. No need to touch the modulation (PWM).
> 
> Maybe this is a good and simple followup to this project, @SensorsIot , as it makes it more universally acceptable and closer to the real standard.

For sure you are right and that is the modification needed to adhere to the standard. Thanks a lot for share your work here! Rom
